server:
  port: 8888 # This is the port for the config server itself
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Saicharan421k/microservices-config.git
          clone-on-start: truespring.application.name=config-server
